### ISSUE TITLE
add urban command

### ISSUE THREAD

**Issue by Chew** [Chewbotcca/IRC#138]

**Comment by Chew** [comment]
We need a good `urban` gem. I would like the API to provide: Word Name, Definition, Likes/Dislikes, Author.

**Comment by soarn** [comment]
After a google search, I got [this](https://github.com/ryangreenberg/urban_dictionary)
(https://github.com/ryangreenberg/urban_dictionary)

**Comment by Chew** [comment]
Doesn't appear to have anything I want. Only word and definition @Soarn
