### ISSUE TITLE
add youtube command

### ISSUE THREAD

**Issue by Chew** [Chewbotcca/IRC#156]

**Comment by cahcontent** [comment]
YouTube has their own [search API](https://developers.google.com/youtube/v3/docs/search/list), or this [gem looks legit](https://github.com/grosser/youtube_search). I'll experiment with that gem real quick and g e t  b a c k  t o  y o u

**Comment by cahcontent** [comment]
update: cannot seem to get the gem to work

![image](https://user-images.githubusercontent.com/7423779/32584602-2635593a-c4c7-11e7-8330-a852cc568df6.png)
